### ISSUE TITLE
Opening the browser's standard menu by pressing RMB in addition to the Deep menu

### ISSUE THREAD

**Issue by CEHR2005** [deep-foundation/deepcase-app#87] opened 2023-03-31 12:25 UTC
![image](https://user-images.githubusercontent.com/8792220/229118573-3f6a1ccc-cc0c-4e3e-aac1-54e4972f7d58.png)
![image](https://user-images.githubusercontent.com/8792220/229118588-d0d081ee-0a3f-4c9f-83a4-1661a1412938.png)

**Comment by agsagds** [comment] 2023-04-14 18:25
Duplicate of https://github.com/deep-foundation/deepcase/issues/57
Please, close this issue.

**Closed as completed** 2023-04-14 23:18 UTC
