### ISSUE TITLE
Azure WebSocket connection failed 

### ISSUE THREAD

**Issue by CEHR2005** [deep-foundation/deepcase-app#209] opened 2023-09-12 12:23 UTC
### Describe the bug

4915-f2b19a0580970b89.js:57 WebSocket connection to 'wss://senchapencha.deep.foundation/api/gql' failed: Invalid frame header
e.connect @ 4915-f2b19a0580970b89.js:57
e.executeOperation @ 4915-f2b19a0580970b89.js:57
t.subscribe @ 4915-f2b19a0580970b89.js:57
complete @ 4915-f2b19a0580970b89.js:57
t.start @ 4915-f2b19a0580970b89.js:57
t @ 4915-f2b19a0580970b89.js:57
e.getObservableFromLink @ 4915-f2b19a0580970b89.js:57
c @ 4915-f2b19a0580970b89.js:57
e.startGraphQLSubscription @ 4915-f2b19a0580970b89.js:57
e.subscribe @ 4915-f2b19a0580970b89.js:57
(anonymous) @ 4915-f2b19a0580970b89.js:57
uI @ framework-ce84985cd166733a.js:9
oU @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oI @ framework-ce84985cd166733a.js:9
oC @ framework-ce84985cd166733a.js:9
r4 @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9

### Steps to reproduce

There was no apparent reason for this

### Environment

```shell
## System:
 - OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
 - CPU: (4) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
 - Memory: 2.32 GB / 7.69 GB
 - Container: Yes
 - Shell: 5.1.16 - /bin/bash
```

**Comment by konard** [comment] 2023-10-13 18:44
Duplicate of https://github.com/deep-foundation/deepcase-app/issues/223

**Closed as not planned by konard** 2023-10-13 18:44 UTC
Labels: bug
